CREATE OR ALTER PROCEDURE [dbo].[usp_ChangePassword] @UserId INT,@PasswordHash VARCHAR(500) AS
BEGIN SET NOCOUNT ON; BEGIN TRY BEGIN TRANSACTION; UPDATE [dbo].[Users] SET [PasswordHash]=@PasswordHash,[ModifiedDate]=SYSUTCDATETIME() WHERE [UserId]=@UserId; SELECT @@ROWCOUNT; COMMIT; END TRY BEGIN CATCH IF @@TRANCOUNT>0 ROLLBACK; THROW; END CATCH END
GO
