CREATE OR ALTER PROCEDURE [dbo].[usp_UpdateUserProfile] @UserId INT,@Email VARCHAR(255)=NULL,@FullName VARCHAR(200)=NULL AS
BEGIN SET NOCOUNT ON; BEGIN TRY BEGIN TRANSACTION; UPDATE [dbo].[Users] SET [Email]=NULLIF(LTRIM(RTRIM(@Email)),''),[FullName]=NULLIF(LTRIM(RTRIM(@FullName)),''),[ModifiedDate]=SYSUTCDATETIME() WHERE [UserId]=@UserId; SELECT @@ROWCOUNT; COMMIT; END TRY BEGIN CATCH IF @@TRANCOUNT>0 ROLLBACK; THROW; END CATCH END
GO
